
services:
  mmc-minecraft-server:
    build: .
    container_name: minecraft-mmc-server
    ports:
      - "${MMC_MINECRAFT_PORT}:25565"
      - "${MMC_RCON_PORT}:25570"
    volumes:
      - ${MMC_MINECRAFT_FOLDER}:/minecraft
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: bash -c "echo 'I agree' | /minecraft/start.sh"
    deploy:
      resources:
        limits:
          memory: 20G       # Limit memory to 20GB
        reservations:
          memory: 10G        # Reserve 8GB of memory
          cpus: "1.0"  
  bmc-minecraft-server:
    build: .
    container_name: minecraft-bmc-server
    ports:
      - "${BMC_MINECRAFT_PORT}:25565"
      - "${BMC_RCON_PORT}:25570"
    volumes:
      - ${BMC_MINECRAFT_FOLDER}:/minecraft
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: bash -c "echo 'I agree' | /minecraft/start.sh"
    deploy:
      resources:
        limits:
          memory: 20G       # Limit memory to 20GB
        reservations:
          memory: 10G        # Reserve 8GB of memory
          cpus: "1.0"  
